config/routes.rb
Rails.application.routes.draw do
  root 'cinemas#index'
	resources :cinemas do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cinema.rb
class Cinema < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :title, :released_on, :duration, presence: true
  validates :description, length: { minimum: 25 }
  validates :total_gross, numericality: { greater_than_or_equal_to: 0 }
  validates :image_file_name, allow_blank: true, format: {
  with:    /\w+\.(gif|jpg|png|jpeg)\z/i,
  message: "must reference a GIF, JPG, or PNG image"
}
  RATINGS = %w(G PG PG-13 R NC-17)
  validates :rating, inclusion: { in: RATINGS }
	def flop?
    total_gross.blank? || total_gross < 50
  end

  def self.released
    where("released_on <= ?", Time.now).order("released_on desc")
  end

  def average_stars
    reviews.average(:stars)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cinema
  validates :name, presence: true
  validates :comment, length:{ minimum: 4 }
  STARS = [1, 2, 3, 4, 5]
  validates :stars, inclusion: {
    in: STARS,
  message: "must be between 1 and 5"
}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types(:danger)
end

app/controllers/cinemas_controller.rb
class CinemasController < ApplicationController
  def index
    @cinemas = Cinema.all
  end

  def show
    @cinema = Cinema.find(params[:id])
  end

  def new
    @cinema = Cinema.new
  end

  def create
    @cinema = Cinema.new(cinema_params)
    if @cinema.save
      redirect_to @cinema, notice: "Cinema successful created" 
    else
      render :new
    end
  end

  def edit
    @cinema = Cinema.find(params[:id])
  end

  def update
    @cinema = Cinema.find(params[:id])
      if @cinema.update(cinema_params)
          # flash[:notice] = "Cinema successfully update" 
        redirect_to (@cinema), notice: "Cinema successfully updated"
      else
        render :edit
      end
  end

  def destroy
    @cinema = Cinema.find(params[:id])
    @cinema.destroy
    redirect_to @cinema, danger: "Cinema successful deleted!"
  end
private
    
  def cinema_params
    cinema_params =  params.require(:cinema).permit(:title, :description, :rating, :released_on, :total_gross, :cast, :director, :duration, :image_file_name)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
      @cinema = Cinema.find(params[:cinema_id])
      @reviews = @cinema.reviews
  end

  def show
      @cinema = Cinema.find(params[:cinema_id])
      @reviews = @cinema.reviews
  end

  def new
      @cinema = Cinema.find(params[:cinema_id])
      @review = @cinema.reviews.new
  end

  def create
      @cinema = Cinema.find(params[:cinema_id])
      @review = @cinema.reviews.new(review_params)
      if @review.save
          redirect_to cinema_reviews_path(@cinema), notice: "Thanks for your review!"
      else 
        render :new
      end
  end
private

  def review_params
      params.require(:review).permit(:name, :comment, :stars)
  end

  def set_movie
      @cinema = Cinema.find(params[:cinema])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cinemas_helper.rb
module CinemasHelper
	def format_total_gross(cinema)
      if cinema.flop?
          content_tag(:strong, 'Flop!')
      else
          # number_to_currency(cinema.total_gross.to_f.round(2))
          number_to_currency(cinema.total_gross)
      end
  end

  def image_for(movie)    

    if cinema.image_file_name.blank?
      image_tag('placeholder.png')
    else
      image_tag(cinema.image_file_name)
    end
  end
  
  def format_average_stars(cinema)
    if cinema.average_stars.nil?
        content_tag(:strong, 'No reviews')
    else
        # "*" * cinema.average_stars.round
        pluralize(number_with_precision(cinema.average_stars, precision: 1) , 'star')
    end
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cinemas/_form.haml
= form_for(@cinema) do |c|
  = render 'shared/errors', object: @cinema
  %fieldset
    %ol
      %li
        %p
          = c.label :title
        %p 
          = c.text_field :title
      %li
        %p
          = c.label :description
        %p
          = c.text_area :description, cols: 50, rows: 10
      %li
        %p
          = c.label :rating 
        %p
          = c.select :rating, Cinema::RATINGS, prompt:"Pick One"
      %li
        %p
          = c.label :released_on
        %p
          = c.date_field :released_on
      %li
        %p
          = c.label :total_gross
        %p
          = c.text_field :total_gross
      %li
        %p
          = c.label :cast
        %p
          = c.text_field :cast
      %li
        %p
          = c.label :director
        %p
          = c.text_field :director
      %li
        %p
          = c.label :duration
        %p
          = c.text_field :duration, size: 10
      %li
        %p
          = c.label :image_file_name
        %p
          = c.text_field :image_file_name
  
      %p
        = c.submit 
        = link_to  "Cancel", root_path

app/views/cinemas/edit.haml
%h1 Editing Cinema 
= render 'form'

app/views/cinemas/index.haml
= link_to("All Cinemas",root_path)
= link_to("Add New Cinema", new_cinema_path)
%h1 Cinemas
%ul
  - @cinemas.each do |cinema|
    %li
      %strong
        = link_to(cinema.title, cinema_path(cinema)) 
        = "(#{cinema.rating})"
      %p
        Description: #{truncate(cinema.description, length: 60, separator: ' ')}
      %p
        -# = time_ago_in_words(cinema.released_on)
        -# ago
        Released Date : #{cinema.released_on.to_s(:released_date)}
      %p
        Price: #{format_total_gross(cinema)}
      %p 
        Cast: #{cinema.cast}
      %p 
        Director: #{cinema.director}
      %p 
        Duration: #{cinema.duration} 

app/views/cinemas/new.haml
%h1 Create new Cinema
= render 'form'

app/views/cinemas/show.haml
%h1 show page
%p
  - if @cinema.image_file_name.nil?
    = image_tag('placeholder.png')
  - else
    = image_tag(@cinema.image_file_name)
%h3 
  = @cinema.title
%p
  = @cinema.description
%p  
  Rate: #{@cinema.rating}
%p  
  Released Date: #{@cinema.released_on}
%p 
  Price: $#{@cinema.total_gross}
%p
  Cast: #{@cinema.cast}
%p
  Director: #{@cinema.director}
%p
  Duration: #{@cinema.duration}
%p
  = format_average_stars(@cinema)
= link_to "Edit", edit_cinema_path(@cinema)
= link_to "Delete", cinema_path(@cinema), method: :delete, data:{ confirm: 'Are your want to delete this Cinema?'}
= link_to "Cancel", root_path
= link_to pluralize(@cinema.reviews.size, "Review"),cinema_reviews_path(@cinema)
= link_to "Write Review ", new_cinema_review_path(@cinema), class: 'button ok reivew'

app/views/layouts/_flash.haml
- flash.each do |key, value|
    = content_tag(:p, value, :class => "flash#{key}")

app/views/layouts/_footer.haml
%footer#page-footer
  %h3
    Copyright &copy; 2019
    = link_to 'The Pragmatic Studio','http://pragmaticstudio.com'

app/views/layouts/_header.haml
%header#page-header
  %h1 Flix Cinema
  #wrapper
    - if flash[:notice]
      %p.flash.notice
        = flash[:notice]
    - if flash[:alert]
      %p.flash.alert
        = flash[:alert]

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flix</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Add Favicon on Rails -->
    <%= favicon_link_tag asset_path('cinema.png') %>
  </head>
  <body>
    <%= render 'layouts/header'%>
    <%= yield %>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/reviews/index.haml
%ol#reviews
  - @reviews.each do |review|
    %li 
      %span.review
        = "#{pluralize(review.stars, 'star')}"
      %span.user
        = "#{review.name}"
      %span.data
        = time_ago_in_words(review.created_at)
      = "#{review.comment}"
= link_to"Back to all Cinema", root_path(@cinema)
      

app/views/reviews/new.haml
%header#content-header
  %h1 
    = link_to(@cinema.title, @cinema) 
  = form_for([@cinema, @review]) do |f|
    = render 'shared/errors', object: @cinema
    %fieldset
      %ol
        %li.required
          %p 
            = f.label :name
          %p
            = f.text_field :name, size: 40, autofocus: true
        %li.required_stars
          %p 
            = f.label :stars
          %p
            = f.select :stars, Review::STARS, prompt: "Pick one"
        %li.required
          %p 
            = f.label :comment
          %p
            = f.text_area :comment, col: 80, placeholder: "What do you think?"
        %p 
          = f.submit 'Post Review'
          = link_to "Cancel", @cinema, class: 'button'

app/views/shared/_errors.haml
- if @cinema.errors.any?
  %section#errors
    %header 
      %h2
        Oops ! The #{@cinema.class.name.titleize.downcase}could not be save.
      %h3 
        Please correct the following #{pluralize(@cinema.errors.count, "error")}:
    %ul 
      - @cinema.errors.full_messages.each do |message|
        %li=message
-# - if @review.errors.any?
-#   %section#errors
-#     %header 
-#       %h2
-#         Oops ! The #{@review.class.name.titleize.downcase}could not be save.
-#       %h3 
-#         Please correct the following #{pluralize(@review.errors.count, "error")}:
-#     %ul 
-#       - @review.errors.full_messages.each do |message|
-#         %li=message